version: "3.8"

services:

  db:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: backend-go
    build: ./GO_API
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SERVER_PORT: 8080
      MONGO_URI: mongodb://db:27017/

  frontend:
    image: frontend-angular
    build: ./frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data:
